/*
 * This file is part of OpenOrion2
 * Copyright (C) 2021 Martin Doucha
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef LANG_H_
#define LANG_H_

#define BILL_RESEARCH_COST 61
#define BILL_PURE_RESEARCH 62

#define ESTR_OFFICER_HIRE_COST 1
#define ESTR_OFFICER_TOO_EXPENSIVE 4

#define ESTR_MONSTER_ANTARANS 657
#define ESTR_MONSTER_GUARDIAN 658
#define ESTR_MONSTER_AMOEBA 172
#define ESTR_MONSTER_CRYSTAL 245
#define ESTR_MONSTER_DRAGON 271
#define ESTR_MONSTER_EEL 280
#define ESTR_MONSTER_HYDRA 323

#define ESTR_CLIMATE_TOXIC 538
#define ESTR_CLIMATE_RADIATED 718
#define ESTR_CLIMATE_BARREN 719
#define ESTR_CLIMATE_DESERT 720
#define ESTR_CLIMATE_TUNDRA 721
#define ESTR_CLIMATE_OCEAN 398
#define ESTR_CLIMATE_SWAMP 500
#define ESTR_CLIMATE_ARID 183
#define ESTR_CLIMATE_TERRAN 722
#define ESTR_CLIMATE_GAIA 302

#define ESTR_NO_FARMING 386

#define ESTR_LMINERALS_ULTRA_POOR 683
#define ESTR_LMINERALS_POOR 422
#define ESTR_LMINERALS_ABUNDANT 684
#define ESTR_LMINERALS_RICH 449
#define ESTR_LMINERALS_ULTRA_RICH 685

#define ESTR_OFFICER_HIRE_BUTTON_TITLE 320
#define ESTR_OFFICER_HIRE_BUTTON_DESC 505
#define ESTR_OFFICER_REJECT_BUTTON_TITLE 446
#define ESTR_OFFICER_REJECT_BUTTON_DESC 506

#define ESTR_RACENAME_ALKARI 644
#define ESTR_LGRAVITY_LOW 686

#define ESTR_PLANET_SIZE_TINY 682
#define ESTR_PLANET_SIZE_SMALL 479
#define ESTR_PLANET_SIZE_MEDIUM 370
#define ESTR_PLANET_SIZE_LARGE 359
#define ESTR_PLANET_SIZE_HUGE 322

#define ESTR_RTOPIC_HYPER 643

#define ESTR_SPECIAL_NONE 696

#define ESTR_SKILLNAME_ASSASSIN 723
#define ESTR_SKILLNAME_ASSASSIN_ADV 724
#define ESTR_SKILLNAME_COMMANDO 725
#define ESTR_SKILLNAME_COMMANDO_ADV 726
#define ESTR_SKILLNAME_DIPLOMAT 622
#define ESTR_SKILLNAME_DIPLOMAT_ADV 727
#define ESTR_SKILLNAME_ENGINEER 728
#define ESTR_SKILLNAME_ENGINEER_ADV 729
#define ESTR_SKILLNAME_ENVIRONMENTALIST 730
#define ESTR_SKILLNAME_ENVIRONMENTALIST_ADV 731
#define ESTR_SKILLNAME_FAMOUS 732
#define ESTR_SKILLNAME_FAMOUS_ADV 733
#define ESTR_SKILLNAME_FARMING_LEADER 734
#define ESTR_SKILLNAME_FARMING_LEADER_ADV 735
#define ESTR_SKILLNAME_FIGHTER_PILOT 736
#define ESTR_SKILLNAME_FIGHTER_PILOT_ADV 737
#define ESTR_SKILLNAME_FINANCIAL_LEADER 738
#define ESTR_SKILLNAME_FINANCIAL_LEADER_ADV 739
#define ESTR_SKILLNAME_GALACTIC_LORE 740
#define ESTR_SKILLNAME_GALACTIC_LORE_ADV 741
#define ESTR_SKILLNAME_HEMLSMAN 742
#define ESTR_SKILLNAME_HEMLSMAN_ADV 743
#define ESTR_SKILLNAME_INSTRUCTOR 744
#define ESTR_SKILLNAME_INSTRUCTOR_ADV 745
#define ESTR_SKILLNAME_LABOR_LEADER 746
#define ESTR_SKILLNAME_LABOR_LEADER_ADV 747
#define ESTR_SKILLNAME_MEDICINE 748
#define ESTR_SKILLNAME_MEDICINE_ADV 749
#define ESTR_SKILLNAME_MEGAWEALTH 750
#define ESTR_SKILLNAME_MEGAWEALTH_ADV 751
#define ESTR_SKILLNAME_NAVIGATOR 752
#define ESTR_SKILLNAME_NAVIGATOR_ADV 753
#define ESTR_SKILLNAME_OPERATIONS 754
#define ESTR_SKILLNAME_OPERATIONS_ADV 755
#define ESTR_SKILLNAME_ORDNANCE 756
#define ESTR_SKILLNAME_ORDNANCE_ADV 757
#define ESTR_SKILLNAME_RESEARCHER 758
#define ESTR_SKILLNAME_RESEARCHER_ADV 759
#define ESTR_SKILLNAME_SCIENCE_LEADER 760
#define ESTR_SKILLNAME_SCIENCE_LEADER_ADV 761
#define ESTR_SKILLNAME_SECURITY 671
#define ESTR_SKILLNAME_SECURITY_ADV 762
#define ESTR_SKILLNAME_SPIRITUAL_LEADER 763
#define ESTR_SKILLNAME_SPIRITUAL_LEADER_ADV 764
#define ESTR_SKILLNAME_SPY_MASTER 765
#define ESTR_SKILLNAME_SPY_MASTER_ADV 766
#define ESTR_SKILLNAME_TACTICS 767
#define ESTR_SKILLNAME_TACTICS_ADV 768
#define ESTR_SKILLNAME_TELEPATH 769
#define ESTR_SKILLNAME_TELEPATH_ADV 770
#define ESTR_SKILLNAME_TRADER 771
#define ESTR_SKILLNAME_TRADER_ADV 772
#define ESTR_SKILLNAME_WEAPONRY 773
#define ESTR_SKILLNAME_WEAPONRY_ADV 774

#define ESTR_LEADER_LEVEL_COMMANDER 775
#define ESTR_LEADER_LEVEL_ADMIN 781

#define ESTR_SAVEFILE_BROKEN 787
#define ESTR_SAVESLOT_AUTO 790

#define HELP_TECH_COLONY_SHIP 41
#define HELP_TECH_OUTPOST_SHIP 109
#define HELP_TECH_TRANSPORT 189

// Galaxy screen
#define HELP_GALAXY_STARDATE_BOX 284
#define HELP_GALAXY_GAME_BUTTON 285
#define HELP_GALAXY_TREASURY_INFO 286
#define HELP_GALAXY_FLEET_INFO 288
#define HELP_GALAXY_FOOD_INFO 290
#define HELP_GALAXY_FREIGHTER_INFO 291
#define HELP_GALAXY_RESEARCH_INFO 292
#define HELP_GALAXY_COLONIES_BUTTON 293
#define HELP_GALAXY_PLANETS_BUTTON 294
#define HELP_GALAXY_FLEETS_BUTTON 295
#define HELP_GALAXY_TURN_BUTTON 296
#define HELP_GALAXY_LEADERS_BUTTON 297
#define HELP_GALAXY_RACES_BUTTON 298
#define HELP_GALAXY_INFO_BUTTON 299
#define HELP_GALAXY_ZOOM_BUTTON 300
#define HELP_GALAXY_MULTIPLAYER_TURN_LIGHTS 303

// Leader list screen
#define HELP_LEADERLIST_ADMINS_BUTTON 313
#define HELP_LEADERLIST_CAPTAINS_BUTTON 314
#define HELP_LEADERLIST_STAR_SYSTEM 315
#define HELP_LEADERLIST_ADMIN_LIST 316
#define HELP_LEADERLIST_STAR_DESCRIPTION 318
#define HELP_LEADERLIST_MINIMAP_LABEL 322
#define HELP_LEADERLIST_HIRE 323
#define HELP_LEADERLIST_POOL 324
#define HELP_LEADERLIST_DISMISS 325
#define HELP_LEADERLIST_RETURN 326
#define HELP_LEADERLIST_CAPTAIN_LIST 328
#define HELP_LEADERLIST_SHIP_DESCRIPTION 329
#define HELP_LEADERLIST_SHIP_GRID 333
#define HELP_LEADERLIST_SCROLLBAR 334

// Planet list screen
#define HELP_PLANETLIST_SLOT 337
#define HELP_PLANETLIST_HEADER 338
#define HELP_PLANETLIST_MINIMAP 343
#define HELP_PLANETLIST_SCROLLBAR 345
#define HELP_PLANETLIST_CLIMATE_BUTTON 348
#define HELP_PLANETLIST_MINERALS_BUTTON 349
#define HELP_PLANETLIST_SIZE_BUTTON 350
#define HELP_PLANETLIST_ENEMY_TOGGLE 351
#define HELP_PLANETLIST_GRAVITY_TOGGLE 352
#define HELP_PLANETLIST_ENV_TOGGLE 353
#define HELP_PLANETLIST_MINERAL_TOGGLE 354
#define HELP_PLANETLIST_RANGE_TOGGLE 355
#define HELP_PLANETLIST_COLONY_TOGGLE 356
#define HELP_PLANETLIST_OUTPOST_TOGGLE 357
#define HELP_PLANETLIST_RETURN_BUTTON 358

// Fleet screen
#define HELP_FLEET_MINIMAP 359
#define HELP_FLEET_SHIP_GRID 360
#define HELP_FLEET_SCROLLBAR 361
#define HELP_FLEET_NAME_BAR 363
#define HELP_FLEET_PREV_BUTTON 364
#define HELP_FLEET_NEXT_BUTTON 365
#define HELP_FLEET_SHIP_INFO 366
#define HELP_FLEET_ALL_BUTTON 368
#define HELP_FLEET_RELOCATE_BUTTON 369
#define HELP_FLEET_SCRAP_BUTTON 370
#define HELP_FLEET_LEADERS_BUTTON 371
#define HELP_FLEET_SUPPORT_TOGGLE 372
#define HELP_FLEET_COMBAT_TOGGLE 373
#define HELP_FLEET_RETURN_BUTTON 374

// In-game menu
#define HELP_GAMEMENU_SAVE 416
#define HELP_GAMEMENU_LOAD 417
#define HELP_GAMEMENU_NEWGAME 418
#define HELP_GAMEMENU_QUIT 419
#define HELP_GAMEMENU_SETTINGS 422
#define HELP_GAMEMENU_RETURN 423

// Main menu
#define HELP_MAINMENU_CONTINUE 645
#define HELP_MAINMENU_LOAD 646
#define HELP_MAINMENU_NEWGAME 647
#define HELP_MAINMENU_MULTIPLAYER 648
#define HELP_MAINMENU_SCORES 649
#define HELP_MAINMENU_QUIT 650

#define HSTR_SPECTRAL_CLASS_DESCRIPTIONS 14

#define HSTR_WEAPON_ARC_360 73

#define HSTR_STAR_UNEXPLORED 147

#define HSTR_SHIPINFO_BEAM_OCV 152
#define HSTR_SHIPINFO_BEAM_DCV 153
#define HSTR_SHIPINFO_DESTINATION_KNOWN 154
#define HSTR_SHIPINFO_DESTINATION_UNKNOWN 155
#define HSTR_SHIPINFO_WEAPONS 156
#define HSTR_SHIPINFO_SPECIALS 157
#define HSTR_SHIPINFO_NONE 158

#define HSTR_SAVEFILE_NOT_FOUND 177

#define HSTR_MAINMENU_ASK_NEWGAME 185
#define HSTR_MAINMENU_ASK_QUIT 186

#define HSTR_SAVESLOT_STARDATE 217
#define HSTR_PLAYER_SELECT_FMT 251

#define HSTR_SHIPCLASS_OUTPOST 257
#define HSTR_SHIPCLASS_OUTPOST_PLURAL 258
#define HSTR_SHIPCLASS_TRANSPORT 259
#define HSTR_SHIPCLASS_TRANSPORT_PLURAL 260
#define HSTR_SHIPCLASS_COLONY 261
#define HSTR_SHIPCLASS_COLONY_PLURAL 262

#define HSTR_OFFICER_HIRE_COST 263
#define HSTR_OFFICER_MAINT_COST 264
#define HSTR_OFFICER_FREE_MAINT 265
#define HSTR_OFFICER_IN_POOL 266
#define HSTR_OFFICER_UNASSIGNED 266
#define HSTR_OFFICER_FOR_HIRE_TIME 268

#define HSTR_OFFICER_DEFINITE_ARTICLE 271
#define HSTR_OFFICER_LOCATION_POOL 272
#define HSTR_OFFICER_LOCATION_NONE 273
#define HSTR_OFFICER_LOCATION_REFIT 274
#define HSTR_OFFICER_LOCATION_MISSING 275

#define HSTR_OFFICER_ASSIGN_SLOW 279
#define HSTR_OFFICER_ASSIGN_INSTANT 280

#define HSTR_OFFICER_TOO_EXPENSIVE 290
#define HSTR_OFFICER_COST1 291
#define HSTR_OFFICER_COST 292

#define HSTR_OFFICER_ASSIGN_NONCOMBAT 299
#define HSTR_FLEET_OFFICER_ETA 302
#define HSTR_FLEET_RACE_DETAIL_FMT 304

#define HSTR_PLANET_FOOD 320
#define HSTR_PLANET_PRODUCTION_PENALTY 321
#define HSTR_PLANET_POPULATION 322
#define HSTR_BLACK_HOLE 324
#define HSTR_PLANETLIST_NO_PLANETS 334
#define HSTR_PLANET_PRODUCTION 337

#define HSTR_STARSYSTEM_GAS_GIANT_INFO 350
#define HSTR_STARSYSTEM_ASTEROIDS_INFO 351
#define HSTR_STARSYSTEM_WORMHOLE_INFO 363

#define HSTR_COLONY_POPULATION 384

#define HSTR_SAVESLOT_EMPTY 387

#define JIM2_DEFINITE_ARTICLE 61

#define KEN_WEAPON_ARC_FWD 3
#define KEN_SHIPCREW_GREEN 31

#define TNAME_RTOPIC_STARTING_TECH 0
#define TNAME_TECH_NONE 83
#define TNAME_BUILDING_NONE 295

#define TNAME_SPECIALTYPE_NONE 344
#define TNAME_SHIELDTYPE_NONE 391
#define TNAME_WEAPONTYPE_NONE 397
#define TNAME_WEAPONTYPE_NONE_PLURAL 496

#define TNAME_SHIPCLASS_FRIGATE 542
#define TNAME_SHIPCLASS_DESTROYER 543
#define TNAME_SHIPCLASS_CRUISER 544
#define TNAME_SHIPCLASS_BATTLESHIP 545
#define TNAME_SHIPCLASS_TITAN 546
#define TNAME_SHIPCLASS_DOOMSTAR 547

#define TNAME_SHIPCLASS_FRIGATE_PLURAL 551
#define TNAME_SHIPCLASS_DESTROYER_PLURAL 552
#define TNAME_SHIPCLASS_CRUISER_PLURAL 553
#define TNAME_SHIPCLASS_BATTLESHIP_PLURAL 554
#define TNAME_SHIPCLASS_TITAN_PLURAL 555
#define TNAME_SHIPCLASS_DOOMSTAR_PLURAL 556

#endif
