/*
 * This file is part of OpenOrion2
 * Copyright (C) 2021 Martin Doucha
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef LANG_H_
#define LANG_H_

#define ESTR_CLIMATE_TOXIC 538
#define ESTR_CLIMATE_RADIATED 718
#define ESTR_CLIMATE_BARREN 719
#define ESTR_CLIMATE_DESERT 720
#define ESTR_CLIMATE_TUNDRA 721
#define ESTR_CLIMATE_OCEAN 398
#define ESTR_CLIMATE_SWAMP 500
#define ESTR_CLIMATE_ARID 183
#define ESTR_CLIMATE_TERRAN 722
#define ESTR_CLIMATE_GAIA 302

#define ESTR_LMINERALS_ULTRA_POOR 683
#define ESTR_LMINERALS_POOR 422
#define ESTR_LMINERALS_ABUNDANT 684
#define ESTR_LMINERALS_RICH 449
#define ESTR_LMINERALS_ULTRA_RICH 685

#define ESTR_RACENAME_ALKARI 644
#define ESTR_LGRAVITY_LOW 686

#define ESTR_PLANET_SIZE_TINY 682
#define ESTR_PLANET_SIZE_SMALL 479
#define ESTR_PLANET_SIZE_MEDIUM 370
#define ESTR_PLANET_SIZE_LARGE 359
#define ESTR_PLANET_SIZE_HUGE 322

#define ESTR_SPECIAL_NONE 696

// Galaxy screen
#define HELP_GALAXY_GAME_BUTTON 285
#define HELP_GALAXY_COLONIES_BUTTON 293
#define HELP_GALAXY_PLANETS_BUTTON 294
#define HELP_GALAXY_FLEETS_BUTTON 295
#define HELP_GALAXY_TURN_BUTTON 296
#define HELP_GALAXY_LEADERS_BUTTON 297
#define HELP_GALAXY_RACES_BUTTON 298
#define HELP_GALAXY_INFO_BUTTON 299
#define HELP_GALAXY_ZOOM_BUTTON 300

// Planet list screen
#define HELP_PLANETLIST_SLOT 337
#define HELP_PLANETLIST_HEADER 338
#define HELP_PLANETLIST_MINIMAP 343
#define HELP_PLANETLIST_SCROLLBAR 345
#define HELP_PLANETLIST_ENEMY_TOGGLE 351
#define HELP_PLANETLIST_GRAVITY_TOGGLE 352
#define HELP_PLANETLIST_ENV_TOGGLE 353
#define HELP_PLANETLIST_MINERAL_TOGGLE 354
#define HELP_PLANETLIST_RANGE_TOGGLE 355
#define HELP_PLANETLIST_RETURN_BUTTON 358

// Fleet screen
#define HELP_FLEET_MINIMAP 359
#define HELP_FLEET_SHIP_GRID 360
#define HELP_FLEET_SCROLLBAR 361
#define HELP_FLEET_NAME_BAR 363
#define HELP_FLEET_PREV_BUTTON 364
#define HELP_FLEET_NEXT_BUTTON 365
#define HELP_FLEET_SHIP_INFO 366
#define HELP_FLEET_ALL_BUTTON 368
#define HELP_FLEET_RELOCATE_BUTTON 369
#define HELP_FLEET_SCRAP_BUTTON 370
#define HELP_FLEET_LEADERS_BUTTON 371
#define HELP_FLEET_SUPPORT_TOGGLE 372
#define HELP_FLEET_COMBAT_TOGGLE 373
#define HELP_FLEET_RETURN_BUTTON 374

// In-game menu
#define HELP_GAMEMENU_SAVE 416
#define HELP_GAMEMENU_LOAD 417
#define HELP_GAMEMENU_NEWGAME 418
#define HELP_GAMEMENU_QUIT 419
#define HELP_GAMEMENU_SETTINGS 422
#define HELP_GAMEMENU_RETURN 423

// Main menu
#define HELP_MAINMENU_CONTINUE 645
#define HELP_MAINMENU_LOAD 646
#define HELP_MAINMENU_NEWGAME 647
#define HELP_MAINMENU_MULTIPLAYER 648
#define HELP_MAINMENU_SCORES 649
#define HELP_MAINMENU_QUIT 650

#define HSTR_PLANET_FOOD 320
#define HSTR_PLANET_PRODUCTION_PENALTY 321
#define HSTR_PLANET_POPULATION 322
#define HSTR_BLACK_HOLE 324
#define HSTR_PLANETLIST_NO_PLANETS 334
#define HSTR_PLANET_PRODUCTION 337

#endif
